version: '3.5'
services:
  main:
    container_name: main
    build:
      context: .
      target: build_stage
    command: npm run start:dev
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:
    external: true
